field/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, re_path, path
from kdl_ldap.signal_handlers import \
    register_signal_handlers as kdl_ldap_register_signal_hadlers
from wagtail.core import urls as wagtail_urls
from wagtail.admin import urls as wagtailadmin_urls
from wagtail.documents import urls as wagtaildocs_urls
from puput import urls as puput_urls
from django.conf.urls import url
kdl_ldap_register_signal_hadlers()

admin.autodiscover()

# https://docs.wagtail.io/en/v2.4/advanced_topics/
# settings.html?highlight=urls.py#urls-py
urlpatterns = [
    path('admin/', admin.site.urls),
    re_path(r'^wagtail/', include(wagtailadmin_urls)),
    re_path(r'^documents/', include(wagtaildocs_urls)),
    re_path(r'^captcha/', include('captcha.urls')),

    # For anything not caught by a more specific rule above, hand over to
    # Wagtail's serving mechanism
    url(r'', include(puput_urls)),
    re_path(r'', include(wagtail_urls)),
]

# -----------------------------------------------------------------------------
# Django Debug Toolbar URLS
# -----------------------------------------------------------------------------
try:
    if settings.DEBUG:
        import debug_toolbar
        urlpatterns = [
            re_path(r'^__debug__/', include(debug_toolbar.urls)),
        ] + urlpatterns
except ImportError:
    pass

# -----------------------------------------------------------------------------
# Static file DEBUGGING
# -----------------------------------------------------------------------------
if settings.DEBUG:
    from django.conf.urls.static import static
    from django.contrib.staticfiles.urls import staticfiles_urlpatterns
    import os.path

    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(settings.MEDIA_URL + 'images/',
                          document_root=os.path.join(settings.MEDIA_ROOT,
                                                     'images'))

field_wagtail/models.py
import json
from typing import Union, Dict, Any

import wagtail
from django import forms
from django.conf import settings
from django.db import models
from django.http.response import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from django.utils.text import Truncator
from dublincore_resource.models import (DublinCoreAgent, DublinCoreRights)
from kdl_wagtail.core.models import (BaseRichTextPage, BasePage)
from modelcluster.fields import ParentalKey
from modelcluster.models import ClusterableModel
from puput.models import EntryPage
from wagtail.admin.edit_handlers import (
    FieldPanel, InlinePanel
)
from wagtail.contrib.routable_page.models import route, RoutablePageMixin
from wagtail.core.fields import RichTextField
from wagtail.core.models import (Page, Orderable)
from wagtail.images.edit_handlers import ImageChooserPanel
from wagtail.images.models import (
    Image,
    AbstractImage,
    AbstractRendition
)
from wagtail.snippets.edit_handlers import SnippetChooserPanel
from wagtail.snippets.models import register_snippet

from django_kdl_timeline.models import (
    AbstractTimelineEventSnippet,
    AbstractDublinCoreWagtailMediaResource,
    AbstractTimelinePage
)


class HomePage(BaseRichTextPage):
    parent_page_types = ['wagtailcore.Page']

    def get_context(self, request):
        ret = super().get_context(request)

        ret['communities_root'] = Page.objects.filter(
            slug=settings.FIELD_COMMUNITIES_ROOT_SLUG
        ).first()

        ret['news'] = EntryPage.objects.filter(
            live=True
        ).order_by('-first_published_at')

        Image = wagtail.images.get_image_model()

        ret['media_images'] = Image.objects.filter(
            tags__name='homepage'
        ).order_by('?')

        return ret

    @classmethod
    def can_create_at(cls, parent):
        # You can only create one of these!
        return (super(HomePage, cls).can_create_at(parent)
                and not cls.objects.exists())


class MailingListForm(forms.Form):
    email = forms.EmailField()
    first_name = forms.CharField(max_length=64)
    last_name = forms.CharField(max_length=64)
    agree = forms.BooleanField(
        label='I agree with below statement', required=True)


class MailingListFormPage(RoutablePageMixin, BasePage):
    success_message = models.TextField(
        help_text='Confirmation message to users who have just signed up',
        blank=True
    )
    error_message = models.TextField(
        help_text='Error message in case the use cannot re-subscribe',
        blank=True
    )

    content_panels = BasePage.content_panels + [
        FieldPanel('success_message', classname='full'),
        FieldPanel('error_message', classname='full')
    ]

    @route(r'^$')
    def serve_form(self, request):
        context = self.get_context(request)
        if context['submitted_code']:
            # then redirect to confirmation page
            return HttpResponseRedirect(
                self.get_url(request) + self.reverse_subpage(
                    'mailinglist_submitted',
                    args=(context['submitted_code'],)
                )
            )
        else:
            return super(MailingListFormPage, self).serve(request)

    def get_context(self, request):
        ret = super().get_context(request)
        ret['submitted_code'] = 0

        if request.method == 'POST':
            form = MailingListForm(request.POST)
            if form.is_valid():
                # we sign them up with mailchimp API
                from .utils import MailingList
                mailing_list = MailingList()

                error = mailing_list.subscribe({
                    'EMAIL': form.cleaned_data['email'],
                    'FNAME': form.cleaned_data['first_name'],
                    'LNAME': form.cleaned_data['last_name'],
                    # 'ORG': form.cleaned_data['organisation'],
                })

                ret['submitted_code'] = error
        else:
            form = MailingListForm()

        ret['hide_footer_mailing_list'] = True
        ret['mailing_list_form'] = form

        return ret

    @route(r'^submitted-(\d+)/$', name='mailinglist_submitted')
    def serve_newsletter_signed(self, request, submitted_code=None):

        submitted_code = int(submitted_code or 0)

        return render(
            request,
            'field_wagtail/mailing_list_submitted_page.html',
            {
                'page': self,
                'submitted_code': submitted_code,
                'hide_footer_mailing_list': True,
            }
        )


class FieldTimelineResourceImage(Orderable, models.Model):
    image_rendition = 'width-400'
    thumb_rendition = 'width-50'

    resource = ParentalKey(
        'FieldTimelineResource',
        on_delete=models.CASCADE,
        null=True,
        related_name='related_images'
    )

    image = models.ForeignKey(
        Image,
        on_delete=models.CASCADE,
        null=True
    )

    panels = [
        ImageChooserPanel('image')
    ]

    @property
    def rendition_url(self) -> str:
        if self.image:
            try:
                return self.image.get_rendition(self.image_rendition).url
            except Exception:
                pass
        return ''

    @property
    def thumbnail_url(self) -> str:
        if self.image:
            try:
                return self.image.get_rendition(self.thumb_rendition).url
            except Exception:
                pass
        return ''

    def __str__(self):
        return str(self.resource) + '/' + self.image.filename

    class Meta:
        verbose_name = 'Timeline Resource'


class FieldTimelineResource(ClusterableModel,
                            AbstractDublinCoreWagtailMediaResource):
    filename = models.CharField(max_length=256, blank=False, null=False,
                                default='')
    image_ref = models.CharField(max_length=256, blank=True)
    caption = models.TextField(blank=True, default='')
    credit = models.CharField(max_length=256, blank=True)
    link_url = models.CharField(max_length=512, null=True)
    resource_type = models.CharField(
        max_length=64, choices=[
            ('I', 'IMAGE'),
            ('D', 'DOCUMENT'),
            ('A', 'AUDIO'),
            ('V', 'VIDEO')],
        default='I'
    )
    panels = AbstractDublinCoreWagtailMediaResource.panels + [
        InlinePanel('related_images', label="Images"),
    ]

    @property
    def attached_media(self) -> Union[None, FieldTimelineResourceImage]:
        """ Return the attached resource
        currently only images, but video and perhaps audio could be added"""
        if self.resource_type == 'I':
            img = FieldTimelineResourceImage.objects.filter(resource=self)
            if img and img.count() > 0:
                return img[0]
        return None

    def to_timeline_media(self) -> Dict[str, Any]:
        """Transform to a timelineJS media object"""
        url = ''
        if self.resource_type == 'I' and self.attached_media:
            url = self.attached_media.rendition_url
        if len(url) > 0:
            media_data = {'url': url,
                          'thumbnail': self.attached_media.thumbnail_url, }
            if len(self.caption) > 0:
                media_data['caption'] = self.caption
            if len(self.attached_media.image.default_alt_text) > 0:
                media_data[
                    'alt'] = self.attached_media.image.default_alt_text
            photographer = ''
            if self.creators and self.creators.count() > 0:
                photographer = ', '.join(
                    [creator.full_name for creator in self.creators.all()]
                )
            if len(photographer) > 0 and len(self.credit) > 0:
                media_data['credit'] = "{} / {}".format(
                    photographer,
                    self.credit
                )
            elif len(photographer) > 0:
                media_data['credit'] = "{}".format(
                    photographer,
                )
            elif len(self.credit) > 0:
                media_data['credit'] = self.credit
            if self.link_url and len(self.link_url) > 0:
                media_data['link'] = self.link_url
            return media_data
        return {'url': url}

    def __str__(self):
        return "{}".format(
            self.identifier
        )


class FieldTimelineCategory(models.Model):
    category_name = models.CharField(max_length=256, blank=True)

    class Meta:
        verbose_name = "Timeline Category"
        verbose_name_plural = "Timeline Categories"

    def __str__(self):
        return self.category_name


class FieldOralHistory(models.Model):
    timeline_event = models.ForeignKey(
        'FieldTimelineEvent',
        on_delete=models.PROTECT, null=True
    )
    speaker = models.CharField(
        max_length=256, blank=False, null=False, default=''
    )
    place = models.CharField(
        max_length=256, blank=False, null=False, default=''
    )
    era = models.CharField(
        max_length=128, blank=False, null=False, default=''
    )
    text = models.TextField(blank=True, default='')
    rights = models.ForeignKey(
        DublinCoreRights,
        null=True, blank=True,
        on_delete=models.SET_NULL
    )

    class Meta:
        verbose_name = "Oral History"
        verbose_name_plural = "Oral Histories"

    def __str__(self):
        return "{}:{}".format(
            self.speaker,
            Truncator(self.text).words(10)
        )


"""An event in the FIELD timeline, inherited from slide"""


class FieldTimelineEvent(AbstractTimelineEventSnippet):
    category = models.ForeignKey('FieldTimelineCategory',
                                 on_delete=models.PROTECT, null=True)
    tier = models.IntegerField(null=False, blank=False, default=0)
    resource = models.ForeignKey('FieldTimelineResource',

templates/field_wagtail/field_dublin_core_resource_list_page.html
{% extends "kdl_wagtail_page/rich_page.html" %}
{% load kdl_wagtail_core_tags wagtailcore_tags wagtailimages_tags resource_tags %}


{% block main %}
    {{ page.body|richtext }}
    <ul>
        {% for resource_item in page.resource_items.all %}
            <li>
            {% if resource_item.resource.wagtail_image %}
                {% image resource_item.resource.wagtail_image width-400 as custom_image %}
                <img src="{{ custom_image.url }}" width="{{ custom_image.width }}"
    height="{{ custom_image.height }}" alt="{{ custom_image.alt_text }}" />
            {% endif %}
            <br/>
            {{ resource_item.resource.title }}
            </li>
        {% endfor %}
    </ul>

{% endblock %}

templates/field_wagtail/field_timeline_page.html
{% extends "base.html" %}
{% load wagtailcore_tags %}

{% block meta_title %}Timeline{% endblock %}

{% block title %}
    Timeline
{% endblock %}

{% block css %}
    <link title="timeline-styles" rel="stylesheet"
          href="https://cdn.knightlab.com/libs/timeline3/latest/css/timeline.css">
{% endblock %}

{% block main %}
    <div id='timeline-embed' style="width: 100%; height: 600px"></div>
{% endblock %}

{% block footer_scripts %}
    <script src="https://cdn.knightlab.com/libs/timeline3/latest/js/timeline.js"></script>
    <script type="text/javascript">
        var options = {
            hash_bookmark: true,
            zoom_sequence: [0.1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89],
            initial_zoom: 0,
            scale_factor: 0.1,
            marker_height_min: 50,
            marker_width_min: 150,
            timenav_height_min: 300,
            dragging: true,
            optimal_tick_width: 150,
        }
        var timeline_json = '{{ timeline_json_url }}';
        window.timeline = new TL.Timeline('timeline-embed', timeline_json, options);
        //
        $(window).on("load", function(){
            $("#timeline-embed").click(function(ev){
                //
                if (ev.target){
                    if ($(ev.target).attr('class') == "{{ ev_target_class }}"){
                        ev.preventDefault();
                        if (timeline){
                            timeline.goToId($(ev.target).data("uniqueId"));
                        }
                    }
                }
            });

        });
    </script>
{% endblock %}

templates/field_wagtail/home_page.html
{% extends "kdl_wagtail_core/base_page.html" %}
{% load kdl_wagtail_core_tags wagtailcore_tags wagtailimages_tags %}
{% block meta_title %}{% endblock %}
{% block page-header %}
{% endblock page-header %}
{% block page-body %}
<div class="home">
  <section class="carousel">
    <div id="carousel">
      <img alt="" src="https://images.pexels.com/photos/158179/lake-constance-sheep-pasture-sheep-blue-158179.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2">
      <img alt="" src="https://images.pexels.com/photos/288621/pexels-photo-288621.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260">
      <img alt="" src="https://images.pexels.com/photos/97317/pexels-photo-97317.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2">
      <img alt="" src="https://images.pexels.com/photos/1276237/pexels-photo-1276237.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260">
    </div>
  </section>
  <section class="intro">
    {{ page.body|richtext }}
    <div class="readmore"><a href="about">Read more</a></div>
  </section>
  <section class="media">
    <header>
      <h2>Media</h2>
    </header>
    {% for image in media_images|slice:":4" %}
    <div class="card">
      {% image image fill-360x180 %}
      <div class="overlay">
        <h3 class="truncated-text padded-text">{{ image.title }}</h3>
      </div>
    </div>
    {% endfor %}
  </section>
  <section class="blog">
    <header>
      <h2><a href="/blog-news/">Latest</a></h2>
    </header>
    {% for news_item in news|slice:":4" %}
    <div class="card">
      <a href="{{ news_item.get_url }}">
        {% image news_item.header_image width-400 %}
        <div class="overlay">
          <h3 class="truncated-text padded-text">{{ news_item.title }}</h3>
        </div>
      </a>
    </div>
    {% endfor %}
  </section>
  {% if 0 %}
  <section class="paper">
    <header>
      <h2>Papers</h2>
    </header>
    <ul>
      <li>Lorem ipsum dolor sit amet</li>
      <li>Qualisque erroribus consectetuer sit et, id eam volutpat</li>
      <li>Eam ex dicit dolorum</li>
      <li>Stet volutpat ne nec</li>
      <li>Eu elitr consetetur mediocritatem vim</li>
    </ul>
  </section>
  {% endif %}
</div>
{% endblock page-body %}

templates/field_wagtail/mailing_list_form_page.html
{% extends "kdl_wagtail_core/base_page.html" %}
{% load kdl_wagtail_core_tags wagtailcore_tags wagtailimages_tags staticfiles %}


{% block page-body %}
<div class="mailing-list-page">
    <div class="page-introduction">
        {{ page.introduction|richtext }}
    </div>

    <form action="" method="post" class="form-mailing-list">
        {% csrf_token %}

        <ul>
            {{ mailing_list_form.as_ul }}
        </ul>

        <p>
            <label for="id_agree" class="consent-text">
              By providing my details I am consenting to FIELD team
              sending me information about the project,
              such as news, bulletins and events.
              <a target="_blank" href="https://www.kcl.ac.uk/terms/privacy.aspx">
                King’s College London’s privacy policy applies.
              </a>
            </label>
        </p>

        <p>
            <input class="field-button" type="submit" value="Sign up" />
        </p>
    </form>
</div>

{% endblock page-body %}

templates/field_wagtail/mailing_list_submitted_page.html
{% extends "kdl_wagtail_core/base_page.html" %}
{% load kdl_wagtail_core_tags wagtailcore_tags wagtailimages_tags staticfiles %}


{% block page-body %}
<div class="mailing-list-submitted">
    <div class="page-introduction">
        {% if submitted_code < 100 %}
            {{ page.success_message|richtext }}
        {% else %}
            {{ page.error_message|richtext }}
        {% endif %}
        <br>
    </div>
</div>

{% endblock page-body %}